### ISSUE TITLE
[Tooltip]Tooltip is invalid on ios & android

### ISSUE THREAD

**Issue by BooYeu** [gluestack/gluestack-ui#1640]
### Description

I try https://snack.expo.dev/@viraj_10/tooltip-native-onpress, but I still can't open tooltip on ios&android

### CodeSandbox/Snack link

https://snack.expo.dev/@viraj_10/tooltip-native-onpress

### Steps to reproduce

I try https://snack.expo.dev/@viraj_10/tooltip-native-onpress, but I still can't open tooltip on ios&android

### gluestack-ui Version

1.0.35

### Platform

- [ ] Expo
- [ ] React Native CLI
- [ ] Next
- [ ] Web
- [X] Android
- [X] iOS

**Comment by RishabhSahu24** [comment]
@BooYeu 

The 'tooltip-native-onpress' feature is operational on both iOS and Android, activated by a long press on the respective views. However, it's worth noting that when using a mobile device, it is necessary to hold the button for a brief duration. If the press is too quick, the hover effect may not become visible. Likewise, on the web, the hover effect might not be triggered if the cursor is moved rapidly, adhering to the anticipated behavior.


https://github.com/gluestack/gluestack-ui/assets/108934337/3f292e4c-878e-4e22-ba35-9b18ce01d273

**Comment by BooYeu** [comment]
Can you add some props to show tooltip when use click it ? Because users rarely long press something in ios&android

**Comment by Viraj-10** [comment]
@BooYeu, As shown in example. we are using `onPressIn` and `onPressOut` to control `isOpen` prop in tooltip.
You can choose any event which you feel is right for your application and control `isOpen` prop. 
You can use `onPress` to `toggle isOpen` or fire a custom event which makes `isOpen` false. 
Closing this issue, Since tooltip is working on native platform. You can further open discussion.
