### ISSUE TITLE
Generated Box / VStack / HStack & others use div for web, not View. This breaks onLayout.

### ISSUE THREAD

**Issue by OneHatRepo** [gluestack/gluestack-ui#2524]
### Description

onLayout should work on web, the same as it does for native, but doesn't because components are using divs, not Views

### CodeSandbox/Snack link

https://github.com/OneHatRepo/Gluestack-Error

### Steps to reproduce

```
npm i
npm run web
```

App.js will error with "Warning: Unknown event handler property `onLayout`. It will be ignored. at div"

Is there a reason that these web components use divs instead of Views, like the non-web version does? I'm wanting to use the onLayout prop, but it's unavailable. I'm sure there are other API elements of View that div doesn't support as well.

For cross-platform development, these need to be the same—please use Views for them all!

I'm seeing the same thing in Box, Card, Center, Grid, HStack, Skeleton, and VStack.

### gluestack-ui Version

latest

### Platform

- [X] Expo
- [ ] React Native CLI
- [ ] Next
- [X] Web
- [ ] Android
- [ ] iOS

**Comment by OneHatRepo** [comment]
Yes, but 1) the files will reappear again whenever I run the generation, and 2) it breaks cross-platform consistency to use divs on web. Why have them in the first place?

(I'm a firm believer in not tearing down a fence before you know why it was put up in the first place, so I'm asking why these are here.)

**Comment by Viraj-10** [comment]
Hey @OneHatRepo,  
If you need to use `onLayout` or other `View` prop-based functionality, make sure to import `View` directly from `react-native` instead of using `Box` or other gluestack-ui components.

### Why?
This separation ensures compatibility with React Server Components (RSC) for our layout components.

### Does it affect consistency?
No, it doesn’t. When rendering with `react-native-web`, `View` translates to a `<div>` with custom styling. We apply this same styling to our layout components, ensuring they behave consistently.


I hope this clarifies your questions. I'll go ahead and close the issue, but feel free to leave a comment if you have any further questions.

**Comment by OneHatRepo** [comment]
@Viraj-10 But it _does_ affect consistency, not in style but in usage; because in native, a developer can add a <VStack onLayout={() => {}} /> and on web he can't. 

I have components that use onLayout both in native and web, and I can't use them on web, because I get an error.

**Comment by OneHatRepo** [comment]
For anyone who finds this issue later—I explicitly import the native version when I need to use onLayout, and this works fine.
