### ISSUE TITLE
Icon rendering very small inside Button component

### ISSUE THREAD

**Issue by ethandpowers** [gluestack/gluestack-ui#524]
### Description

When using icons inside of a button component, the icon renders at a fraction of it's expected size.  The size does not appear to change even when using size, w, and h props or when wrapping in large Center component.

### Steps to reproduce

1. Use the following inside a view:
```
<Button>
    <InfoIcon mr="$2" color="$white" />
    <Button.Text>Some Text</Button.Text>
</Button>
```
2. Run on iOS simulator.
3. Button icon renders super small

### gluestack-ui Version

0.1.13

### Platform

- [ ] Android
- [X] Expo
- [X] iOS
- [ ] Next

**Comment by sandeepgeeky** [comment]
@ethandpowers  Could you share the snack link or a sandbox link?

**Comment by akash3gtm** [comment]
@ethandpowers We've made `Button.Icon` that changes size when the size prop is passed to `Button` component.

```
<Button size="someSize">
    <Button.Icon as={InfoIcon} mr="$2"/>
    <Button.Text>Some Text</Button.Text>
</Button>
```

If you still want to override the Icon styling, you can use `h` and `w` props in `Button.Icon`.
We'll highly recommend to use `Button.Icon` instead of either `Icon` or directly using some Icon.

**Comment by mattaningram** [comment]
Ideally we would be able to use the `<Icon>` component as shown in @akash3gtm example and pass in a size prop since I often want a different size for the icon than the defaults set by the button. That way you don't have to pass both `h` and `w` and can use the preset Icon sizes for overrides.

**Comment by makkarMeenu** [comment]
Hey
This is a known issue. `_icon` written in Button styles as descendant is being overridden. We can't pass inline variants. We will try to resolve this asap.
For more clarity:

This size passed in Button.Icon is not working as size is a variant.
``` 
<Button>
 <Button.Icon as={Add}  size="xl" />
</Button>
```

For now, hack would be:
```
<Button>
 <Button.Icon as={Add}  h="$8" w="$8" />
</Button>
```

**Comment by makkarMeenu** [comment]
We worked towards this and tried multiple things which works best for the users and is easy to customise as well.
For better understanding, 
- `tag` in html is equivalent to `baseStyle` in `gluestack-style`
- `class`  in html is equivalent to `variant` in `gluestack-style`
- `inline-styles`  in html is equivalent to `inline-props` in `gluestack-style`

In the above case, 

```
<Button>
   <Button.Icon as={Add}  />
</Button>
```
Button has some default size variant as `md` . 
We can assume the above code to be 

```
<Button size="md" >
   <Button.Icon as={Add}  />
</Button>
```

So, html equivalent for understanding will be, 
```
<div class="size-md" >
   <p>Hello</p>
</div>


.size-md {
background-color: yellow;
}
```

The bg of div will be blue and text will be black(default).

For the case you want to achieve, 

```
<Button size="md">
 <Button.Icon as={Add}  size="sm" />
</Button>
```
html equivalent: 

```
<div class="size-md" >
   <p class="size-sm" >Hello</p>
</div>


.size-md {
background-color: yellow;
}
.size-md p {
    color: red;
}
.size-sm {
     color: blue;
}
```
The color of the text will be red instead of blue which justifies that `Button.Icon`'s size can not be overridden.
In simpler words, `Icon`  linked to `Button` cannot be overridden for a specific variant. You can surely change the style properties of an Icon but not the variant. 

For achieving something like, 

```
<Button>
 <Button.Icon as={Add}  size="xl" />
</Button>
```

It will be better to use `<Icon>`  instead of `<Button.Icon>` because that will not have the reference of `Button` and can be styled separately.

We are open for discussions on the above. Would be great if we can find the best solution.
